export const getEditorConfig = () => ({
  readonly: false,
  enter: "P",
  enterBlock: "p",
  placeholder: "",
  toolbarAdaptive: false,
  uploader: {
    insertImageAsBase64URI: true,
    files: (files) => Array.from(files),
  },
  buttons: [
    // Text
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "superscript",
    "subscript",
    "|",

    // Font
    "font",
    "fontsize",
    "brush",
    "|",

    // Lists
    "ul",
    "ol",
    "align",
    "indent",
    "outdent",
    "|",

    // Media
    "image",
    "link",
    "table",
    "|",

    // Utilities
    "undo",
    "redo",
    "cut",
    "copy",
    "paste",
    "copyformat",
    "selectall",
    "find",
    "|",

    // Code / Display
    "source",
    "fullsize",
    "preview",
    "print",
    "|",

    // Cleanup + Custom class
    "eraser",
    "hr",
  ],
  style: {
    font: [
      "Arial",
      "Georgia",
      "Impact",
      "Tahoma",
      "Times New Roman",
      "Verdana",
      "Courier New",
      "Comic Sans MS",
      "Lucida Console",
      "Trebuchet MS",
    ],
    background: [
      "#ffffff",
      "#000000",
      "#f44336",
      "#e91e63",
      "#9c27b0",
      "#673ab7",
      "#3f51b5",
      "#2196f3",
      "#03a9f4",
      "#00bcd4",
      "#009688",
      "#4caf50",
      "#8bc34a",
      "#cddc39",
      "#ffeb3b",
      "#ffc107",
      "#ff9800",
      "#ff5722",
    ],
    color: [
      "#000000",
      "#ffffff",
      "#f44336",
      "#e91e63",
      "#9c27b0",
      "#673ab7",
      "#3f51b5",
      "#2196f3",
      "#03a9f4",
      "#00bcd4",
      "#009688",
      "#4caf50",
      "#8bc34a",
      "#cddc39",
      "#ffeb3b",
      "#ffc107",
      "#ff9800",
      "#ff5722",
    ],
  },
  events: {
    afterInsertImage: (node) => {},
    error: (error) => {},
  },
});
